Vagrant.configure("2") do |config|
    if Vagrant.has_plugin?("vagrant-vbguest")
      config.vbguest.auto_update = false
    end
    config.vm.define "leaf01" do |leaf01|
        leaf01.vm.box = "CumulusCommunity/cumulus-vx"
        leaf01.vm.network "private_network", virtualbox__intnet: "mgmt-network", auto_config: false 
        leaf01.vm.network "private_network", virtualbox__intnet: "PP11", auto_config: false  # spine01 <--> leaf01
        leaf01.vm.network "private_network", virtualbox__intnet: "PP21", auto_config: false  # spine02 <--> leaf01
        leaf01.vm.network "private_network", virtualbox__intnet: "PP101", auto_config: false  # leaf01 <--> server01
        leaf01.vm.provision "shell", path: "noob/leaf01.sh"
        leaf01.vm.provider "virtualbox" do |vbox|
            vbox.name = "CumulusVX - Leaf01"
            vbox.customize ['modifyvm', :id, '--nicpromisc2', 'allow-vms']
            vbox.customize ['modifyvm', :id, '--nicpromisc3', 'allow-vms']
            vbox.customize ['modifyvm', :id, '--nicpromisc4', 'allow-vms']
        end    
    end
    config.vm.define "leaf02" do |leaf02|
        leaf02.vm.box = "CumulusCommunity/cumulus-vx"
        leaf02.vm.network "private_network", virtualbox__intnet: "mgmt-network", auto_config: false 
        leaf02.vm.network "private_network", virtualbox__intnet: "PP12", auto_config: false  # spine01 <--> leaf02
        leaf02.vm.network "private_network", virtualbox__intnet: "PP22", auto_config: false  # spine02 <--> leaf02
        leaf02.vm.network "private_network", virtualbox__intnet: "PP201", auto_config: false  # leaf02 <--> server01
        leaf02.vm.provision "shell", path: "noob/leaf02.sh"
        leaf02.vm.provider "virtualbox" do |vbox|
            vbox.name = "CumulusVX - Leaf02"
            vbox.customize ['modifyvm', :id, '--nicpromisc2', 'allow-vms']
            vbox.customize ['modifyvm', :id, '--nicpromisc3', 'allow-vms']
            vbox.customize ['modifyvm', :id, '--nicpromisc4', 'allow-vms']
        end    
    end
    config.vm.define "leaf03" do |leaf03|
        leaf03.vm.box = "CumulusCommunity/cumulus-vx"
        leaf03.vm.network "private_network", virtualbox__intnet: "mgmt-network", auto_config: false 
        leaf03.vm.network "private_network", virtualbox__intnet: "PP13", auto_config: false  # spine01 <--> leaf03
        leaf03.vm.network "private_network", virtualbox__intnet: "PP23", auto_config: false  # spine02 <--> leaf03
        leaf03.vm.network "private_network", virtualbox__intnet: "PP302", auto_config: false  # leaf03 <--> server02
        leaf03.vm.provision "shell", path: "noob/leaf03.sh"
        leaf03.vm.provider "virtualbox" do |vbox|
            vbox.name = "CumulusVX - Leaf03"
            vbox.customize ['modifyvm', :id, '--nicpromisc2', 'allow-vms']
            vbox.customize ['modifyvm', :id, '--nicpromisc3', 'allow-vms']
            vbox.customize ['modifyvm', :id, '--nicpromisc4', 'allow-vms']
        end    
    end
    config.vm.define "leaf04" do |leaf04|
        leaf04.vm.box = "CumulusCommunity/cumulus-vx"
        leaf04.vm.network "private_network", virtualbox__intnet: "mgmt-network", auto_config: false 
        leaf04.vm.network "private_network", virtualbox__intnet: "PP14", auto_config: false  # spine01 <--> leaf04
        leaf04.vm.network "private_network", virtualbox__intnet: "PP24", auto_config: false  # spine02 <--> leaf04 
        leaf04.vm.network "private_network", virtualbox__intnet: "PP402", auto_config: false  # leaf04 <--> server02 
        leaf04.vm.provision "shell", path: "noob/leaf04.sh"
        leaf04.vm.provider "virtualbox" do |vbox|
            vbox.name = "CumulusVX - Leaf04"
            vbox.customize ['modifyvm', :id, '--nicpromisc2', 'allow-vms']
            vbox.customize ['modifyvm', :id, '--nicpromisc3', 'allow-vms']
            vbox.customize ['modifyvm', :id, '--nicpromisc4', 'allow-vms']
        end    
    end
    config.vm.define "spine01" do |spine01|
        spine01.vm.box = "CumulusCommunity/cumulus-vx"
        spine01.vm.network "private_network", virtualbox__intnet: "mgmt-network", auto_config: false 
        spine01.vm.network "private_network", virtualbox__intnet: "PP11", auto_config: false  # spine01 <--> leaf01
        spine01.vm.network "private_network", virtualbox__intnet: "PP12", auto_config: false  # spine01 <--> leaf02
        spine01.vm.network "private_network", virtualbox__intnet: "PP13", auto_config: false  # spine01 <--> leaf03
        spine01.vm.network "private_network", virtualbox__intnet: "PP14", auto_config: false  # spine01 <--> leaf04
        spine01.vm.provision "shell", path: "noob/spine01.sh"
        spine01.vm.provider "virtualbox" do |vbox|
            vbox.name = "CumulusVX - Spine01"
            vbox.customize ['modifyvm', :id, '--nicpromisc2', 'allow-vms']
            vbox.customize ['modifyvm', :id, '--nicpromisc3', 'allow-vms']
            vbox.customize ['modifyvm', :id, '--nicpromisc4', 'allow-vms']
            vbox.customize ['modifyvm', :id, '--nicpromisc5', 'allow-vms']
        end
    end    
    config.vm.define "spine02" do |spine02|
        spine02.vm.box = "CumulusCommunity/cumulus-vx"
        spine02.vm.network "private_network", virtualbox__intnet: "mgmt-network", auto_config: false 
        spine02.vm.network "private_network", virtualbox__intnet: "PP21", auto_config: false  # spine02 <--> leaf01
        spine02.vm.network "private_network", virtualbox__intnet: "PP22", auto_config: false  # spine02 <--> leaf02
        spine02.vm.network "private_network", virtualbox__intnet: "PP23", auto_config: false  # spine02 <--> leaf03 
        spine02.vm.network "private_network", virtualbox__intnet: "PP24", auto_config: false  # spine02 <--> leaf04
        spine02.vm.provision "shell", path: "noob/spine02.sh"
        spine02.vm.provider "virtualbox" do |vbox|
            vbox.name = "CumulusVX - Spine02"
            vbox.customize ['modifyvm', :id, '--nicpromisc2', 'allow-vms']
            vbox.customize ['modifyvm', :id, '--nicpromisc3', 'allow-vms']
            vbox.customize ['modifyvm', :id, '--nicpromisc4', 'allow-vms']
            vbox.customize ['modifyvm', :id, '--nicpromisc5', 'allow-vms']
        end
    end    

    config.vm.define "server01" do |server01|
        server01.vm.box = "generic/ubuntu1804"
        server01.vm.network "private_network", virtualbox__intnet: "mgmt-network", ip: "10.2.3.201", netmask: '255.255.255.0' 
        server01.vm.network "private_network", virtualbox__intnet: "PP101", ip: "10.2.2.17", netmask: '255.255.255.254'  # leaf01 <--> server01
        server01.vm.network "private_network", virtualbox__intnet: "PP201", ip: "10.2.2.19", netmask: '255.255.255.254'   # leaf02 <--> server01
        server01.vm.provider "virtualbox" do |vbox|
            vbox.name = "Ubuntu18.04 - Server1"
            vbox.customize ['modifyvm', :id, '--nicpromisc2', 'allow-vms']
            vbox.customize ['modifyvm', :id, '--nicpromisc3', 'allow-vms']
        end
    end    
    config.vm.define "server02" do |server02|
        server02.vm.box = "generic/ubuntu1804"
        server02.vm.network "private_network", virtualbox__intnet: "mgmt-network", ip: "10.2.3.202", netmask: '255.255.255.0' 
        server02.vm.network "private_network", virtualbox__intnet: "PP302", ip: "10.2.2.21", netmask: '255.255.255.254'   # leaf03 <--> server02
        server02.vm.network "private_network", virtualbox__intnet: "PP402", ip: "10.2.2.23", netmask: '255.255.255.254'   # leaf04 <--> server02
        server02.vm.provider "virtualbox" do |vbox|
            vbox.name = "Ubuntu18.04 - Server2"
            vbox.customize ['modifyvm', :id, '--nicpromisc2', 'allow-vms']
            vbox.customize ['modifyvm', :id, '--nicpromisc3', 'allow-vms']
        end
    end    
    config.vm.define "auto01" do |auto01|
        auto01.vm.box = "generic/ubuntu1804"
        auto01.vm.network "private_network", virtualbox__intnet: "mgmt-network", ip: "10.2.3.200", netmask: '255.255.255.0' 
        auto01.vm.provider "virtualbox" do |vbox|
            vbox.name = "Ubuntu18.04 - Automation Server"
            vbox.customize ['modifyvm', :id, '--nicpromisc2', 'allow-vms']
        end
    end    
end
